# Generated by Django 5.0.1 on 2024-02-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_patient_sampling_frequency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
        migrations.AddField(
            model_name="patient",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="patient_user_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
