# Generated by Django 5.0.1 on 2024-02-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_csvfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patient_user_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
