# Generated by Django 5.0.1 on 2024-03-01 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_alter_patient_patient_user_id_alter_patient_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="patient_user_id",
        ),
    ]
