# Generated by Django 5.0.1 on 2024-03-07 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_csvfile_diagnosis_output_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvfile",
            name="diagnosis_output",
        ),
    ]
