# Generated by Django 5.0.1 on 2024-03-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0012_remove_csvfile_diagnosis_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvfile",
            name="diagnosis_output",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
