# Generated by Django 5.0.1 on 2024-02-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_patient_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="sampling_frequency",
            field=models.FloatField(default=0.0),
        ),
    ]
