# Generated by Django 5.0.1 on 2024-02-29 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_alter_patient_patient_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="csv_file",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="sampling_frequency",
        ),
    ]
