# Generated by Django 5.0.1 on 2024-03-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_remove_patient_patient_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvfile",
            name="diagnosis_output",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="csvfile",
            name="sampling_frequency",
            field=models.FloatField(),
        ),
    ]
